### ISSUE TITLE
This isn't exactly an issue, but is there a way to accomplish this the other way around? As in using GML to code with haxe?

### ISSUE THREAD

**Issue by MonstyrSlayr** [YAL-Haxe/sfgml#16]

**Comment by YellowAfterlife** [comment]
That depends on what do you want it for - people generally use Haxe to have a high-level, strictly typed language, and people use GameMaker to quickly prototype with a tool that has numerous built-in functions, so using GML in Haxe would yield you advantages of neither of two?
